//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.02 at 05:47:33 PM CET 
//


package tp6;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tp6 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tp6
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Responsable }
     * 
     */
    public Responsable createResponsable() {
        return new Responsable();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link Td }
     * 
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link Semestre }
     * 
     */
    public Semestre createSemestre() {
        return new Semestre();
    }

    /**
     * Create an instance of {@link BlocUnite }
     * 
     */
    public BlocUnite createBlocUnite() {
        return new BlocUnite();
    }

    /**
     * Create an instance of {@link RefResponsable }
     * 
     */
    public RefResponsable createRefResponsable() {
        return new RefResponsable();
    }

    /**
     * Create an instance of {@link Debouche }
     * 
     */
    public Debouche createDebouche() {
        return new Debouche();
    }

    /**
     * Create an instance of {@link Parcours }
     * 
     */
    public Parcours createParcours() {
        return new Parcours();
    }

    /**
     * Create an instance of {@link Nom }
     * 
     */
    public Nom createNom() {
        return new Nom();
    }

    /**
     * Create an instance of {@link RefUnite }
     * 
     */
    public RefUnite createRefUnite() {
        return new RefUnite();
    }

    /**
     * Create an instance of {@link Unite }
     * 
     */
    public Unite createUnite() {
        return new Unite();
    }

    /**
     * Create an instance of {@link RefIntervenant }
     * 
     */
    public RefIntervenant createRefIntervenant() {
        return new RefIntervenant();
    }

    /**
     * Create an instance of {@link Ul }
     * 
     */
    public Ul createUl() {
        return new Ul();
    }

    /**
     * Create an instance of {@link Li }
     * 
     */
    public Li createLi() {
        return new Li();
    }

    /**
     * Create an instance of {@link B }
     * 
     */
    public B createB() {
        return new B();
    }

    /**
     * Create an instance of {@link A }
     * 
     */
    public A createA() {
        return new A();
    }

    /**
     * Create an instance of {@link Intervenant }
     * 
     */
    public Intervenant createIntervenant() {
        return new Intervenant();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Master }
     * 
     */
    public Master createMaster() {
        return new Master();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

}
